Added scaffolding and a recipes controller to project.
jdiorio1/RecipeAPI pull request #5
Opened 2023-12-29 22:20 UTC by jdiorio1

This was no small feat! I had an incorrect NuGet package, I was missing something in my Ingredient class (reference to recipes) also had to add some properties to Recipe_Ingredient class to get the composite key for the Recipe_Ingredient table to be recognized and had to add an override for OnModelCreating to get composite key to be picked up by EF. But I did it!!! 

If this looks okay to you my next step will be to create the database.

2023-12-29 23:02 UTC, jdevx requested changes
Overall looking good. However, the controller file either needs to be removed from the pr OR it needs to be slimmed down to an initial item like the constructor or the constructor + 1 function and there needs to be unit tests for it.

You're doing great!

2023-12-29 23:02 UTC, jdevx commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
Also, there should be unit tests for any controller functions.

2023-12-29 23:21 UTC, jdiorio1 commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
When you scaffold a controller all of this code is auto added to the project. I personally did not put any code into RecipesController.cs. That was all generated by EF. I agree, I should've pushed up the DB changes first. The last few I made were adjusted because I couldn't scaffold and was fixing those errors. But yeah, once I fixed them I should've checked in. Although, until the scaffolding worked I wasn't totally sure I had fixed all the issues. 

Since the code in the controller is auto generated and I had planned to go through it at a later time do I need to delete it all now?

2023-12-29 23:24 UTC, jdevx commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
I would say just delete the file so long as it doesn't hurt anything. You can always scaffold the controller at a future date and check in a modified/slimmed down version then.

2023-12-29 23:25 UTC, jdevx commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
Otherwise I'd say leave it for now but I'd want to see unit tests that cover the scenario for not found, etc.

2023-12-30 01:01 UTC, jdiorio1 commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
Okay, so stupid question. I can delete the controller and scaffold again later, but it's going to put all that code back when I do. What would be the objective of deleting it now only to add it back later? Or are you saying that I shouldn't use scaffolding?

2023-12-30 01:15 UTC, jdevx commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
Not a stupid question. Scaffolding isn't all or nothing. So later you can scaffold if you want to just to get started and delete everything but the constructor and maybe the get method (or whatever method you choose to start with). That way you don't have to create and name the controller and setup the constructor and all the attributes. It gives you a shortcut and then as you build in the future all other methods will be manually added as you need. It's just a shortcut to get you started.

2023-12-30 01:17 UTC, jdevx commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
Honestly, once you're comfortable with this all and it's old hat, most of the time you'll just start with a blank file because it's quicker to go based off what you already know then to setup the scaffolding :)

2023-12-30 01:19 UTC, jdiorio1 commented on RecipeAPI/Controllers/RecipesController.cs
> +﻿using System;
Okay, took off the scaffolding and updated the PR.

2023-12-30 01:21 UTC, jdevx approved these changes

2023-12-30 01:22 UTC, merged